[database]
Server = "db"
DatabaseName = "thirdbot"
User = "thirdbot"
Password = "E3K7dFxcz9LbCeRj"

[discord]
Token = "NDY3MTA4Njg1ODM1OTI3NTYy.Dn8yPg.uvpcsD2GMac4Sxaquar4jFH7efc"

[graylog]
Host = "10.42.0.90"
Port = 12201

[comments]
GotThird = [
    "You're the OKest!",
    "I'm sure your mother is proud of you.",
    "Umm, congratulations I guess?",
    "I'm sure firstbot would have a better comment for you.",
    "Don't be so humble, you are not that great.",
    "Contratulations for getting third in a useless competition!",
]
LeaderHeader = [
    "Here's who is the most average!",
    "These people aren't even good enough to win at losing.",
    "I've run out of witty things to type here.",
]
FirstComments = [
    "You're the thirdest!",
    "It's OK, I don't love you either.",
    "Firstbot is disappoint.",
]
LeaderComments = [
    "They say the third movie in a trilogy is the worst. You aren't even that good.",
    "Whatever",
    "I heard firstbot saying mean things about you the other day.",
]
