FROM golang:1.10.3 as builder
WORKDIR /go/src/github.com/moosetheory/thirdbot/web
COPY ./ /go/src/github.com/moosetheory/thirdbot/
RUN CGO_ENABLED=0 GOOS=linux go install -v ./...

FROM alpine:latest
RUN apk --no-cache add tzdata ca-certificates
COPY --from=builder /go/bin/web /app
CMD ["/app"]