version: '3.6'

services:
  db:
    image: mariadb
    restart: always
    env_file:
      - ./thirdbot.dev.env
    environment:
      MYSQL_DATABASE: thirdbot
      MYSQL_USER: thirdbot
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  thirdbot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    image: moosetheory/thirdbot:dev
    restart: always
    volumes:
      - "./config.dev.toml:/config.toml"