version: '3.6'

services:
  db:
    image: mariadb
    restart: always
    env_file:
      - ./thirdbot.env
    environment:
      MYSQL_DATABASE: thirdbot
      MYSQL_USER: thirdbot
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  thirdbot:
    image: moosetheory/thirdbot:0.1.7
    restart: always
    volumes:
      - "./config.toml:/config.toml"