version: '3.6'

services:
  db:
    image: mariadb
    restart: always
    env_file:
      - ./thirdbot.dev.env
    environment:
      MYSQL_DATABASE: thirdbot
      MYSQL_USER: thirdbot
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  thirdbot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    image: moosetheory/thirdbot:dev
    restart: always
    volumes:
      - "./config.dev.toml:/config.toml"
  
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    image: moosetheory/thirdbot_web:dev
    restart: always
    ports:
      - "80:8080"
    volumes:
      - "./config.dev.toml:/config.toml"